---
title: Rajarshi Chattopadhyay's Resume"
author: Rajarshi Chattopadhyay
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles_resume.css', 'resume']
    # set it to true for a self-contained HTML page
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')

# Get the data filtered to only the items tagged as Resume items
my_data <- read_csv('my_data.csv') %>%
  filter(in_resume) #%>% 
  #mutate(
    # Build some custom sections by collapsing others
    #section = case_when(
      #section %in% c('jobs', 'projects') ~ 'work',
      #TRUE ~ section
    #)
  #) 
```

Aside
================================================================================

Summary {#more-info}
--------------------------------------------------------------------------------

A Software Engineer having 4 years experience:<br>
=> [internship on web application development, permanent job on application development and support](https://likarajo.github.io/WorkSamples)<br>
=> [personal and academic projects on applied machine learning and Big Data management and analysis](https://likarajo.github.io/Projects)<br>
=> self-learned system design fundamental<br>
=> [online training and certifications](https://www.youracclaim.com/users/likarajo)<br>

More Info
--------------------------------------------------------------------------------

```{r}
# When in export mode the little dots are unaligned, so fix that. 
if(PDF_EXPORT){
  cat("\nFor a complete list of my work and projects - \nView my CV online at [likarajo.github.io/cv](https://likarajo.github.io/cv)\n")
  cat("\nView this Resume online at [likarajo.github.io/cv/resume](https://likarajo.github.io/cv/resume)\n")
} else {
  cat("\n[<i class='fas fa-download'></i>](https://github.com/likarajo/cv/raw/master/rajarshi_resume.pdf) Download a PDF of this Resume\n")
  cat("\n[<i class='fa fa-external-link'></i>](https://likarajo.github.io/cv) View my CV for a complete list of my work and projects\n")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> likarajo@gmail.com
- <i class="fa fa-linkedin"></i> [linkedin.com/in/likarajo](https://www.linkedin.com/in/likarajo)
- <i class="fa fa-link"></i> [likarajo.github.io](http://likarajo.github.io)
- <i class="fa fa-phone"></i> (469) 380-2696

Technical Skills {#skills}
--------------------------------------------------------------------------------

*Lang*: Java, Python, Scala<br>
*Web*: Spring, Spring Boot<br>
*Big Data*: Hadoop, Spark<br>
*DevOps*: Git, Jenkins, Docker<br>
*Database*: SQL, NoSQL<br>
*Front End*: HTML/CSS/JS<br>
*Cloud*: AWS S3/EC2/EMR, Elastic<br>

Links to my work{#open-source}
--------------------------------------------------------------------------------

My Project repositories:<br>
<i class="fa fa-github"></i> [github.com/likarajo](https://github.com/likarajo)<br>
<i class="fab fa-github-alt"></i> [likarajo.github.io/Projects](https://likarajo.github.io/Projects)<br>

My Digital credentials:<br>
<i class="fa fa-certificate"></i> [youracclaim.com/users/likarajo](https://www.youracclaim.com/users/likarajo)<br>

My Blogs and Articles: <br>
<i class="fa fa-wordpress"></i> [likarajoblogs.wordpress.com](https://likarajoblogs.wordpress.com)<br>
_Also in my LinkedIn profile articles_

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made w/ [**pagedown**](https://github.com/rstudio/pagedown) | [<i class="fa fa-github"></i>](https://github.com/likarajo/cv)

Last updated on `r Sys.Date()`

Main
================================================================================

Rajarshi Chattopadhyay {#title}
--------------------------------------------------------------------------------

Recent Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
my_data %>% print_position('education')
```

Selected Positions {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
my_data %>% print_position('jobs')
```

Selected Projects {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
my_data %>% print_portfolio_r('projects')
```
